"""
Macro definitions

Author:   Yao Li (yaoli@optics.arizona.edu)
Created:  2017/01/09
Version:  2.0

Last modified by Yao: 2017/02/14

"""

import logging

# Marcos

# Eastwest bound massage header type
EW_PATH_COMP_REQ = 0x01
EW_PATH_COMP_REPLY = 0x02
EW_TRAF_SETUP_REQ = 0x03
EW_TRAF_SETUP_REPLY = 0x04
EW_TRAF_TEAR_REQ = 0x05
EW_TRAF_TEAR_REPLY = 0x06
EW_TRAF_TEAR_PATH_REQ = 0x07
EW_OSNR_MONITOR_REQ = 0x08
EW_OSNR_MONITOR_REPLY = 0x09

# node type
NODE_EDGE = 0x01
NODE_INNER = 0x02

# node port type
PORT_REG_IN = 0x01
PORT_REG_OUT = 0x02
PORT_LOCAL_ADD = 0x04
PORT_LOCAL_DROP = 0x08

# link type
LINK_INTRA_DOMAIN = 0x01
LINK_INTER_DOMAIN = 0x02

# ITU_Standards
FLEXIBLE_GRID = 0x01
ITU_C_50 = 0x02
ITU_C_100 = 0x04

# LSP State
LSP_UNPROVISIONED = 0x01
LSP_SETUP_SUCCESS = 0x02
LSP_SETUP_FAIL = 0x03
LSP_TEARDOWN_SUCCESS = 0x04
LSP_TEARDOWN_FAIL = 0x05
LSP_INACTIVE = 0x06

# Route Type
ROUTE_WORKING = 0x01
ROUTE_BACKUP = 0x02
ROUTE_INTRA_REROUTE = 0x03
ROUTE_REROUTE = 0x04

# Traffic Stage
TRAFFIC_WORKING = 0x01
TRAFFIC_REROUTING = 0x02
TRAFFIC_INACTIVE = 0x03
TRAFFIC_STAGE_UNKNOWN = 0X04

# Traffic State
TRAFFIC_RECEIVE_REQUEST = 0x01
TRAFFIC_PATH_COMPUTATION = 0x02
TRAFFIC_PATH_COMPUTATION_SUCCESS = 0x03
TRAFFIC_PATH_COMPUTATION_FAIL = 0x04
TRAFFIC_SETUP = 0x05
TRAFFIC_SETUP_SUCCESS = 0x06
TRAFFIC_SETUP_FAIL = 0x07
TRAFFIC_TEARDOWN = 0x08
TRAFFIC_TEARDOWN_SUCCESS = 0x09
TRAFFIC_TEARDOWN_FAIL = 0x0a
TRAFFIC_INTRA_DOMAIN_REROUTE = 0x0b
TRAFFIC_INTRA_DOMAIN_REROUTE_SUCCESS = 0x0c
TRAFFIC_INTRA_DOMAIN_REROUTE_FAIL = 0x0d
TRAFFIC_ON_BACKUP_PATH = 0x0e
TRAFFIC_STATE_UNKNOWN = 0X0f

# Traffic Type
TRAFFIC_INTRA_DOMAIN = 0x01
TRAFFIC_CROSS_DOMAIN = 0x02

# Protection Type
TRAFFIC_NO_PROTECTION = 0x01
TRAFFIC_1PLUS1_PROTECTION = 0x02
TRAFFIC_REROUTING_RESTORATION = 0x04

# Controller Type
CONTROLLER_CENTRAL = 0x01
CONTROLLER_LOCAL = 0x02

# Timer Type
TIMER_TRAFFIC_SETUP = 0x01
TIMER_TRAFFIC_TEARDOWN = 0x02
TIMER_PATH_COMPUTATION = 0x03
TIMER_OSNR_MONITORING = 0x04

# Message Result
SUCCESS = 0x00
FAIL = 0x01
TIMEOUT_PATH_COMPUTATION = 0x02
TIMEOUT_TRAF_SETUP = 0x03   
TIMEOUT_TRAF_TEARDOWN = 0x04
TIMEOUT_REROUTING = 0x05
TIMEOUT_OSNR_MONITORING = 0x06

#Waiting time:
SOUTH_WAITING_TIME = 30
NORTH_WAITING_TIME = 120
EASTWEST_WAITING_TIME = 30

# action
ACTION_SETUP = 0x01
ACTION_TEARDOWN = 0x02

# OSNR threshold
OSNR_THRESHOLD = 18

# Marcos end

# other parameters

log_level = logging.DEBUG
file_path = 'init_files/Ryu_1/'

# other parameters end

# tmp use

DPID = 17

# tmp use end

